version: "2.0"

volumes:
    database:

services:
    db:
        image: postgres:latest
        ports:
            - "5432" # Random available host port will be chosen, same as -P
        volumes:
            - database:/var/lib/postgresql/data
        environment: &dbenv
            - POSTGRES_USER=jitter
            - POSTGRES_PASSWORD=changeInProduction
            - POSTGRES_DB=jitter
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432

    migrations:
        build: ./db
        environment: *dbenv

    jitter:
        build: .
        ports:
            - "8000:8000" # This is port exposed from the container
        volumes:
            - ./res:/go/src/jitter/res
        environment:
            - POSTGRES_HOST=db
